# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questao', models.CharField(help_text='Insira o texto da questão.', max_length=1000, verbose_name='Texto da Questão')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(help_text='Insira o texto da resposta.', max_length=1000, verbose_name='Texto da Resposta')),
                ('correct', models.BooleanField(default=False, help_text='Esta é a resposta correta?')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='RespostaDiscursiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(help_text='Insira o texto da resposta.', max_length=1000, verbose_name='Texto da Resposta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='QuestaoDiscursiva',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questoes.Questao')),
            ],
            options={
                'verbose_name': 'Questão Discursiva',
                'verbose_name_plural': 'Questões Discursivas',
            },
            bases=('questoes.questao',),
        ),
        migrations.CreateModel(
            name='QuestaoObjetiva',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questoes.Questao')),
            ],
            options={
                'verbose_name': 'Questão Objetiva',
                'verbose_name_plural': 'Questões Objetivas',
            },
            bases=('questoes.questao',),
        ),
        migrations.AddField(
            model_name='respostadiscursiva',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questoes.QuestaoDiscursiva', verbose_name='Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.QuestaoObjetiva', verbose_name='Questao'),
        ),
    ]
